import type { RuntimeStory } from './types'

export const DEMO_RUNTIME_STORY: RuntimeStory = {
  id: 'dreamchord-demo-v1',
  title: '梦弦：第一条故事线',
  version: '2.0',
  initialState: {
    nodeCount: 0,
    realityVersion: 0,
    constantNodeLocked: false,
    characters: { yuki: 'normal', ren: 'normal', miya: 'normal', sora: 'normal', ghost: 'normal' },
    activeUIEvents: [],
  },
  scenes: [
    {
      id: 'empty-1',
      event: 'ON_INIT',
      background: 'illustrations/empty-projects',
      characters: [{ id: 'ghost', state: 'normal', position: 'center' }],
      uiEvents: ['EMPTY PROJECT'],
      dialogue: { role: 'ghost', text: '检测到一个被清空的故事工程。标题还在，人物还在，但所有章节都被折叠进空白。' },
    },
    {
      id: 'empty-2',
      event: 'ON_NODE_VISUALIZE',
      background: 'illustrations/empty-nodes',
      characters: [{ id: 'ghost', state: 'normal', position: 'center' }],
      uiEvents: ['FIRST NODE FOUND'],
      dialogue: { role: '旁白', text: '雪在空白画布前醒来。无数发光节点悬在半空，像被删掉的台词，还在等一个人把它们重新连上。' },
    },
    {
      id: 'classroom-1',
      event: 'ON_NODE_VISUALIZE',
      background: 'bg-classroom',
      characters: [{ id: 'yuki', state: 'normal', position: 'center' }],
      uiEvents: ['SCENE 1-1'],
      dialogue: { role: '旁白', text: '午后的教室很安静。雪的笔记本停在第一页，上面只有一句被反复划掉的话：我不知道怎么开始。' },
    },
    {
      id: 'classroom-2',
      event: 'ON_NODE_VISUALIZE',
      background: 'bg-classroom',
      characters: [{ id: 'yuki', state: 'surprised', position: 'center' }],
      dialogue: { role: 'yuki', text: '又来了……那些发光的点，还有连着它们的线。' },
    },
    {
      id: 'classroom-3',
      event: 'ON_NODE_VISUALIZE',
      background: 'bg-classroom',
      characters: [{ id: 'yuki', state: 'surprised', position: 'center' }],
      dialogue: { role: '旁白', text: '每一个节点里都闪过一段草稿：没有说完的告白、没有抵达的车站、没有名字的人。它们不是幻觉，而是一套正在等待修复的故事编辑器。' },
    },
    {
      id: 'sakura-1',
      event: 'ON_CHARACTER_SPAWN',
      eventTarget: 'ren',
      background: 'bg-sakura',
      characters: [
        { id: 'yuki', state: 'surprised', position: 'left' },
        { id: 'ren', state: 'normal', position: 'right' },
      ],
      uiEvents: ['DELETED TIMELINE'],
      dialogue: { role: 'ren', text: '别装作没看见。你删掉的不是文档，是一条还没来得及活下去的世界线。' },
    },
    {
      id: 'sakura-2',
      event: 'ON_CHARACTER_SPAWN',
      eventTarget: 'ren',
      background: 'bg-sakura',
      characters: [
        { id: 'yuki', state: 'surprised', position: 'left' },
        { id: 'ren', state: 'serious', position: 'right' },
      ],
      dialogue: { role: 'yuki', text: '你是谁？为什么知道我删过那些故事？' },
    },
    {
      id: 'sakura-3',
      event: 'ON_CHARACTER_SPAWN',
      eventTarget: 'ren',
      background: 'bg-sakura',
      characters: [
        { id: 'yuki', state: 'normal', position: 'left' },
        { id: 'ren', state: 'serious', position: 'right' },
      ],
      dialogue: { role: 'ren', text: '我叫影。是旧稿里唯一没被删干净的人。你停笔以后，我就一直站在这条樱花路上，等你回来。' },
    },
    {
      id: 'choice-1',
      event: 'ON_BRANCH_SELECT',
      background: 'bg-sakura',
      characters: [
        { id: 'yuki', state: 'normal', position: 'left' },
        { id: 'ren', state: 'smirk', position: 'right' },
      ],
      uiEvents: ['BRANCH READY'],
      dialogue: { role: 'ren', text: '现在选择吧。你是继续逃走，还是承认自己想把这个故事写完？' },
      choices: ['我只是害怕写坏。', '如果能重来，我想改。', '这不是我一个人的错。'],
      choiceTargets: ['choice-1-a', 'choice-1-b', 'choice-1-c'],
    },
    {
      id: 'choice-1-a',
      event: 'ON_BRANCH_SELECT',
      background: 'bg-sakura',
      characters: [
        { id: 'yuki', state: 'surprised', position: 'left' },
        { id: 'ren', state: 'serious', position: 'right' },
      ],
      uiEvents: ['BRANCH: FEAR'],
      dialogue: { role: 'yuki', text: '我只是害怕写坏。只要不写，就不会让任何人失望。' },
      nextSceneId: 'choice-1-merge',
    },
    {
      id: 'choice-1-b',
      event: 'ON_BRANCH_SELECT',
      background: 'bg-sakura',
      characters: [
        { id: 'yuki', state: 'normal', position: 'left' },
        { id: 'ren', state: 'smirk', position: 'right' },
      ],
      uiEvents: ['BRANCH: REWRITE'],
      dialogue: { role: 'yuki', text: '如果能重来，我想改。我不想再把所有人留在半句台词里。' },
      nextSceneId: 'choice-1-merge',
    },
    {
      id: 'choice-1-c',
      event: 'ON_BRANCH_SELECT',
      background: 'bg-sakura',
      characters: [
        { id: 'yuki', state: 'surprised', position: 'left' },
        { id: 'ren', state: 'serious', position: 'right' },
      ],
      uiEvents: ['BRANCH: DENIAL'],
      dialogue: { role: 'yuki', text: '这不是我一个人的错。故事里的人也应该告诉我，他们想去哪。' },
      nextSceneId: 'choice-1-merge',
    },
    {
      id: 'choice-1-merge',
      event: 'ON_BRANCH_SELECT',
      background: 'bg-sakura',
      characters: [
        { id: 'yuki', state: 'normal', position: 'left' },
        { id: 'ren', state: 'serious', position: 'right' },
      ],
      uiEvents: ['BRANCH MERGED'],
      dialogue: { role: 'ren', text: '这就是分支的意义。选择不是找唯一正确答案，而是让故事承认不同的可能。等它们走到同一个结点时，人物已经变了。' },
    },
    {
      id: 'cafe-1',
      event: 'ON_CONSTANT_NODE_CONTACT',
      background: 'bg-cafe',
      characters: [
        { id: 'yuki', state: 'normal', position: 'left' },
        { id: 'miya', state: 'smile', position: 'right' },
      ],
      uiEvents: ['ANCHOR NODE'],
      dialogue: { role: '旁白', text: '下一幕，咖啡厅的灯没有闪烁。宫学姐坐在窗边，像一枚固定现实的锚点。无论哪条分支走到这里，她都会等雪开口。' },
    },
    {
      id: 'cafe-2',
      event: 'ON_CONSTANT_NODE_CONTACT',
      background: 'bg-cafe',
      characters: [
        { id: 'yuki', state: 'surprised', position: 'left' },
        { id: 'miya', state: 'warm', position: 'right' },
      ],
      dialogue: { role: 'yuki', text: '宫学姐，如果我写错了角色，他们会恨我吗？' },
    },
    {
      id: 'cafe-3',
      event: 'ON_CONSTANT_NODE_CONTACT',
      background: 'bg-cafe',
      characters: [
        { id: 'yuki', state: 'normal', position: 'left' },
        { id: 'miya', state: 'warm', position: 'right' },
      ],
      dialogue: { role: 'miya', text: '角色不是用来被控制的。你要做的，是先听见他们，然后给他们一条能走下去的路。' },
    },
    {
      id: 'memory-1',
      event: 'ON_REALITY_CHANGE',
      background: 'bg-starry',
      characters: [{ id: 'yuki', state: 'normal', position: 'center' }],
      uiEvents: ['MEMORY LENS'],
      dialogue: { role: '旁白', text: '雪想起第一次写故事的时候，她不是为了完成任务，而是因为脑海里有个人一直敲窗。后来作业、比赛、评价一点点压下来，她才把那扇窗关上。' },
    },
    {
      id: 'star-1',
      event: 'ON_REALITY_CHANGE',
      background: 'bg-starry',
      characters: [
        { id: 'yuki', state: 'normal', position: 'left' },
        { id: 'ren', state: 'serious', position: 'right' },
      ],
      uiEvents: ['UNNAMED CHARACTER'],
      dialogue: { role: 'ren', text: '还有一个人一直没被听见。你从来没有给他名字，所以他只能待在空白里。' },
    },
    {
      id: 'editor-1',
      event: 'ON_NODE_CREATE',
      background: 'illustrations/empty-nodes',
      characters: [{ id: 'ghost', state: 'normal', position: 'center' }],
      uiEvents: ['CREATE CHARACTER'],
      dialogue: { role: 'ghost', text: '检测到未命名角色。请写下他的第一句定义。' },
    },
    {
      id: 'editor-2',
      event: 'ON_NODE_CREATE',
      background: 'illustrations/empty-nodes',
      characters: [{ id: 'ghost', state: 'normal', position: 'center' }],
      uiEvents: ['SAVE REALITY'],
      dialogue: { role: 'yuki', text: '你不是空白。你只是还没有被听见。你的名字是，空。' },
    },
    {
      id: 'sora-1',
      event: 'ON_NODE_CREATE',
      background: 'bg-starry',
      characters: [
        { id: 'yuki', state: 'smile', position: 'left' },
        { id: 'sora', state: 'curious', position: 'right' },
      ],
      uiEvents: ['CHARACTER CREATED'],
      dialogue: { role: 'sora', text: '如果我是你写出来的，那我也可以选择自己以后成为什么样的人吗？' },
    },
    {
      id: 'choice-2',
      event: 'ON_BRANCH_SELECT',
      background: 'bg-starry',
      characters: [
        { id: 'yuki', state: 'smile', position: 'left' },
        { id: 'sora', state: 'curious', position: 'right' },
      ],
      uiEvents: ['CHARACTER BRANCH'],
      dialogue: { role: 'yuki', text: '可以。你想先从哪里开始？这一次，我不会替你把路写死。' },
      choices: ['从自己的愿望开始。', '从朋友开始。', '从一次冒险开始。'],
      choiceTargets: ['choice-2-a', 'choice-2-b', 'choice-2-c'],
    },
    {
      id: 'choice-2-a',
      event: 'ON_BRANCH_SELECT',
      background: 'bg-starry',
      characters: [
        { id: 'yuki', state: 'smile', position: 'left' },
        { id: 'sora', state: 'normal', position: 'right' },
      ],
      uiEvents: ['SORA: WISH'],
      dialogue: { role: 'sora', text: '那我想先知道，我真正想要守护什么。不是因为设定需要，而是因为我自己想。' },
      nextSceneId: 'choice-2-merge',
    },
    {
      id: 'choice-2-b',
      event: 'ON_BRANCH_SELECT',
      background: 'bg-starry',
      characters: [
        { id: 'yuki', state: 'smile', position: 'left' },
        { id: 'sora', state: 'normal', position: 'right' },
      ],
      uiEvents: ['SORA: FRIEND'],
      dialogue: { role: 'sora', text: '那我想先成为某个人的朋友，而不是一行角色设定。' },
      nextSceneId: 'choice-2-merge',
    },
    {
      id: 'choice-2-c',
      event: 'ON_BRANCH_SELECT',
      background: 'bg-starry',
      characters: [
        { id: 'yuki', state: 'smile', position: 'left' },
        { id: 'sora', state: 'happy', position: 'right' },
      ],
      uiEvents: ['SORA: ADVENTURE'],
      dialogue: { role: 'sora', text: '那我想去看这个世界的边界。也许那里还有没被写出来的人。' },
      nextSceneId: 'choice-2-merge',
    },
    {
      id: 'choice-2-merge',
      event: 'ON_BRANCH_SELECT',
      background: 'bg-starry',
      characters: [
        { id: 'yuki', state: 'smile', position: 'left' },
        { id: 'sora', state: 'happy', position: 'right' },
      ],
      uiEvents: ['VOICE UNLOCKED'],
      dialogue: { role: '旁白', text: '空的第一条分支被保存了。雪终于明白，创作不是把人物推向结局，而是给他们走向结局的路。' },
    },
    {
      id: 'ending',
      event: 'ON_REALITY_SAVE',
      background: 'illustrations/empty-projects',
      characters: [{ id: 'ghost', state: 'normal', position: 'center' }],
      uiEvents: ['DREAMCHORD READY'],
      dialogue: { role: 'ghost', text: '第一条故事线完成。现在你可以在工作台按章节和场景扩写，在素材库整理人物与背景，在 AI 助手里继续生成分支。' },
    },
  ],
}
